# Generated by Django 5.2.17 on 2026-08-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employerprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='headline',
            field=models.CharField(blank=True, help_text='e.g. Junior Full-Stack Developer', max_length=120),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Optional LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Optional portfolio/GitHub URL'),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short professional summary'),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skill strings (optional, stored as tags)'),
        ),
    ]
