# Generated by Django 5.2.17 on 2026-08-29 18:22

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='submitted_resumes/', validators=[core.validators.validate_resume_file]),
        ),
    ]
